# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIBase.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 581)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.speed_progress = QtWidgets.QProgressBar(self.centralwidget)
        self.speed_progress.setGeometry(QtCore.QRect(40, 500, 731, 20))
        self.speed_progress.setAutoFillBackground(False)
        self.speed_progress.setProperty("value", 0)
        self.speed_progress.setTextVisible(True)
        self.speed_progress.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.speed_progress.setObjectName("speed_progress")
        self.word_current = QtWidgets.QLabel(self.centralwidget)
        self.word_current.setGeometry(QtCore.QRect(110, 170, 611, 141))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(64)
        self.word_current.setFont(font)
        self.word_current.setAcceptDrops(False)
        self.word_current.setAlignment(QtCore.Qt.AlignCenter)
        self.word_current.setObjectName("word_current")
        self.auto_speaker = QtWidgets.QRadioButton(self.centralwidget)
        self.auto_speaker.setEnabled(True)
        self.auto_speaker.setGeometry(QtCore.QRect(30, 20, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.auto_speaker.setFont(font)
        self.auto_speaker.setFocusPolicy(QtCore.Qt.NoFocus)
        self.auto_speaker.setToolTip("")
        self.auto_speaker.setChecked(True)
        self.auto_speaker.setObjectName("auto_speaker")
        self.word_before = QtWidgets.QLabel(self.centralwidget)
        self.word_before.setGeometry(QtCore.QRect(0, 60, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(26)
        self.word_before.setFont(font)
        self.word_before.setAlignment(QtCore.Qt.AlignCenter)
        self.word_before.setObjectName("word_before")
        self.word_explain = QtWidgets.QLabel(self.centralwidget)
        self.word_explain.setEnabled(True)
        self.word_explain.setGeometry(QtCore.QRect(70, 110, 691, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_explain.sizePolicy().hasHeightForWidth())
        self.word_explain.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.word_explain.setFont(font)
        self.word_explain.setInputMethodHints(QtCore.Qt.ImhNone)
        self.word_explain.setScaledContents(False)
        self.word_explain.setAlignment(QtCore.Qt.AlignCenter)
        self.word_explain.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.word_explain.setObjectName("word_explain")
        self.word_status = QtWidgets.QCheckBox(self.centralwidget)
        self.word_status.setEnabled(True)
        self.word_status.setGeometry(QtCore.QRect(120, 20, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.word_status.setFont(font)
        self.word_status.setFocusPolicy(QtCore.Qt.TabFocus)
        self.word_status.setChecked(True)
        self.word_status.setTristate(False)
        self.word_status.setObjectName("word_status")
        self.configButton = QtWidgets.QToolButton(self.centralwidget)
        self.configButton.setGeometry(QtCore.QRect(720, 10, 71, 71))
        self.configButton.setAcceptDrops(False)
        icon = QtGui.QIcon()
        from pkg_resources import resource_filename,Requirement
        headimgpath = resource_filename(Requirement.parse('SmartReview'),'SmartReview/source/headimg.jpg')
        icon.addPixmap(QtGui.QPixmap(headimgpath), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.configButton.setIcon(icon)
        self.configButton.setIconSize(QtCore.QSize(70, 70))
        self.configButton.setAutoExclusive(False)
        self.configButton.setObjectName("configButton")
        self.associationButton = QtWidgets.QPushButton(self.centralwidget)
        self.associationButton.setGeometry(QtCore.QRect(350, 460, 113, 32))
        self.associationButton.setObjectName("associationButton")
        self.associationLabel = QtWidgets.QLabel(self.centralwidget)
        self.associationLabel.setGeometry(QtCore.QRect(40, 430, 721, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.associationLabel.setFont(font)
        self.associationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.associationLabel.setObjectName("associationLabel")
        self.word_explain.raise_()
        self.speed_progress.raise_()
        self.word_current.raise_()
        self.auto_speaker.raise_()
        self.word_before.raise_()
        self.word_status.raise_()
        self.configButton.raise_()
        self.associationButton.raise_()
        self.associationLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "智能复习"))
        self.speed_progress.setFormat(_translate("MainWindow", "已完成: %p%"))
        self.word_current.setText(_translate("MainWindow", "Hello world!"))
        self.auto_speaker.setText(_translate("MainWindow", "智能朗读"))
        self.word_before.setText(_translate("MainWindow", "即将开始"))
        self.word_explain.setText(_translate("MainWindow", "\n"
"int.    打招呼; 哈喽，喂; 你好，您好; 表示问候;\n"
"n.    “喂”的招呼声或问候声;\n"
"vi.    喊“喂”;\n"
""))
        self.word_status.setText(_translate("MainWindow", "已记住"))
        self.configButton.setToolTip(_translate("MainWindow", "配置信息"))
        self.configButton.setText(_translate("MainWindow", "Config"))
        self.associationButton.setText(_translate("MainWindow", "添加混淆词"))
        self.associationLabel.setText(_translate("MainWindow", "混淆词,将会显示在这里..."))

